/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const isLocalhost = Boolean(
  window.location.hostname === "localhost" ||
    // [::1] is the IPv6 localhost address.
    window.location.hostname === "[::1]" ||
    // 127.0.0.1/8 is considered localhost for IPv4.
    window.location.hostname.match(
      /^127(?:\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}$/
    )
);

const awsmobile = {
  "aws_project_region": "sa-east-1",
  "aws_appsync_graphqlEndpoint": "https://euxqpmj4wfbqrbqruddc3dpice.appsync-api.sa-east-1.amazonaws.com/graphql",
  "aws_appsync_region": "sa-east-1",
  "aws_appsync_authenticationType": "API_KEY",
  "aws_appsync_apiKey": "da2-t64nov462fb5tep7d64azmp54y",
  "aws_cognito_identity_pool_id": "sa-east-1:cdf1bb5d-38dd-4368-aabc-11062b290fa4",
  "aws_cognito_region": "sa-east-1",
  "aws_user_pools_id": "sa-east-1_UhhR5PXoY",
  "aws_user_pools_web_client_id": "1hkgk2b7hvst4d9fouq18spdg3",
  "oauth": {
      "domain": "mvr28c6zdotl-staging.auth.sa-east-1.amazoncognito.com",
      "scope": [
          "phone",
          "email",
          "openid",
          "profile",
          "aws.cognito.signin.user.admin"
      ],
      "redirectSignIn": isLocalhost ? "http://localhost:4200/" :  "https://main.d11caeat5g3q4m.amplifyapp.com/",
      "redirectSignOut": isLocalhost ? "http://localhost:4200/" :  "https://main.d11caeat5g3q4m.amplifyapp.com/",
      "responseType": "code"
  },
  "federationTarget": "COGNITO_USER_POOLS",
  "aws_cognito_username_attributes": [],
  "aws_cognito_social_providers": [
      "GOOGLE"
  ],
  "aws_cognito_signup_attributes": [
      "EMAIL"
  ],
  "aws_cognito_mfa_configuration": "OFF",
  "aws_cognito_mfa_types": [
      "SMS"
  ],
  "aws_cognito_password_protection_settings": {
      "passwordPolicyMinLength": 8,
      "passwordPolicyCharacters": []
  },
  "aws_cognito_verification_mechanisms": [
      "EMAIL"
  ]
};


export default awsmobile;
